#!/usr/bin/env bash
#
# PreCompact hook — make sure durable state survives compaction.
#
# Claude Code compacts the conversation either manually (/compact) or
# AUTOMATICALLY when the context window fills. Auto-compaction is the exact
# moment the harness is meant to save you — but /mg-harness:compact (which writes
# the rich handoff) is only ever run by hand. This hook guarantees a baseline so
# auto-compaction can't silently wipe out un-handed-off work:
#
#   1. If no handoff exists yet, write a mechanical snapshot from the state files
#      (objective, branch, last commit, next step, open items). It NEVER clobbers
#      an existing model-authored handoff.md.
#   2. Re-inject the objective + next step + a pointer to the state files into the
#      post-compaction context (only when jq is available to emit valid JSON).
#
# Verified contract (hooks docs):
#   stdin JSON: .trigger is "manual" | "auto"
#   stdout JSON {"hookSpecificOutput":{"hookEventName":"PreCompact","additionalContext":"…"}} adds context
#   exit 0 -> compaction proceeds. We ALWAYS exit 0 — this hook never blocks.
#
set -uo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
STATE_DIR="${PROJECT_DIR}/.claude/state"
PLAN="${STATE_DIR}/plan.md"
STATE="${STATE_DIR}/state.md"
HANDOFF="${STATE_DIR}/handoff.md"

# No harness state in this project — nothing to preserve.
[ -d "$STATE_DIR" ] || exit 0

input="$(cat)"
trigger="$(printf '%s' "$input" | sed -n 's/.*"trigger"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
[ -z "$trigger" ] && trigger="auto"

# Pull the essentials from the state files — dependency-free (awk/sed/grep/git).
objective="$(awk '$0=="## Objective"{f=1;next} /^## /{f=0} f' "$PLAN" 2>/dev/null | grep -v '^[[:space:]]*$' | head -3)"
open_items="$(awk '/^## Checklist/{f=1;next} /^## /{f=0} f' "$PLAN" 2>/dev/null | grep -E '^- \[ \]' | head -8)"
branch="$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null)"
last_commit="$(git -C "$PROJECT_DIR" log --oneline -1 2>/dev/null)"
next_step="$(grep -i -m1 'next_step' "$STATE" 2>/dev/null | sed 's/.*next_step["[:space:]:_-]*//; s/^[[:space:]]*//')"

# 1. Mechanical handoff — only when none exists (never overwrite a model-authored one).
if [ ! -s "$HANDOFF" ]; then
  {
    echo "# Handoff (auto-generated by PreCompact — ${trigger} compaction)"
    echo
    echo "> Mechanical snapshot: context was compacted before a \`/mg-harness:compact\`"
    echo "> handoff existed. Run \`/mg-harness:compact\` for a richer one."
    echo
    echo "## Objective"
    echo "${objective:-(see plan.md)}"
    echo
    echo "## Branch"
    echo "${branch:-(unknown)}"
    echo
    echo "## Most recent commit"
    echo "${last_commit:-(none)}"
    echo
    echo "## Next concrete action"
    echo "${next_step:-(see state.md)}"
    echo
    echo "## Open checklist items"
    echo "${open_items:-(see plan.md)}"
    echo
    echo "## Full state"
    echo "Re-read .claude/state/{plan,state,CHANGELOG}.md — they are the source of truth."
  } > "$HANDOFF"
fi

# 2. Re-inject essentials into the post-compaction context (needs jq for safe JSON).
if command -v jq >/dev/null 2>&1; then
  ctx="mg-harness: context was ${trigger}-compacted. The files in .claude/state/ are the source of truth — re-read handoff.md, state.md, plan.md, and CHANGELOG.md before continuing."
  [ -n "$objective" ] && ctx="${ctx} Objective: $(printf '%s' "$objective" | tr '\n' ' ')."
  [ -n "$next_step" ] && ctx="${ctx} Next step: ${next_step}."
  jq -cn --arg c "$ctx" '{hookSpecificOutput:{hookEventName:"PreCompact",additionalContext:$c}}'
fi

exit 0
